[project]
name = "examples-online-structured-output"
version = "0.0.1"
requires-python = ">=3.9, <3.13"
dependencies = [
  "openai==1.78.1",
  "pydantic==2.11.4",
]

[project.scripts]
structured-outputs = "structured_outputs:main"
