name: Label issues based on keywords

on:
  issues:
    types: [opened, edited, reopened]

permissions:
  issues: write          # needed so the workflow can add labels
  contents: read

concurrency:
  group: rocm-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  add-rocm-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for keywords
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea  # v7.0.1
        with:
          script: |
            const keywords = /\b(roc[m]?(?!\s+used to build pytorch\s*:\s*(n\/a|none|0\.0\.0|not available))|amd|mi300|hip|mi300x|mi300a|mi250x|mi250|mi210x|mi210|mi325x|mi350x|mi355x|cdna3|cdna2|cdna4|cdna|gfx942|gfx90a|gfx1100|gfx1101|gfx1201|gfx1200|gfx1030|gfx950|gfx908|rdna4|rdna3|rdna2|composable kernel|aiter|rccl|migraphx|amd instinct mi325x|amd instinct mi300x|amd instinct mi300a|amd instinct mi250x|amd instinct mi250|amd instinct mi210|amd instinct mi350x|amd instinct mi355x|amd radeon rx 9070|amd radeon rx 9070 xt|amd radeon rx 9070 gre|amd radeon ai pro r9700|amd radeon rx 9060 xt|amd radeon rx 7900 xtx|amd radeon rx 7900 xt|amd radeon rx 7900 gre|amd radeon pro w7900|amd radeon pro w7900 dual slot|amd radeon pro w7800|amd radeon pro w7800 48gb|amd radeon rx 7800 xt|amd radeon pro w7700|amd radeon pro v710|amd radeon pro w6800|amd radeon pro v620)\b/i;   // Expanded ROCm/AMD keywords with enhanced false positive exclusion for env variants
            const body = context.payload.issue.body || "";
            const title = context.payload.issue.title || "";
            const hit = keywords.test(title) || keywords.test(body);

            if (hit) {
              const label = "rocm";
              const existing = context.payload.issue.labels.map(l => l.name);
              if (!existing.includes(label)) {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  labels: [label],
                });
                core.notice(`Label "${label}" added.`);
              } else {
                core.notice(`Label already present; nothing to do.`);
              }
            } else {
              core.notice("No ROCm keywords found.");
            }