name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - run: echo "::add-matcher::.github/workflows/matchers/actionlint.json"
    - run: echo "::add-matcher::.github/workflows/matchers/mypy.json"
    
    - name: Install PyTorch for CPU and NumPy
      run: |
        pip install numpy
        pip install torch==2.6.0 --index-url https://download.pytorch.org/whl/cpu

    - name: Install vLLM Build Dependencies (excluding torch and comments)
      run: pip install $(grep -v 'torch==' requirements/build.txt | grep -v '^#' | tr '\n' ' ')

    - name: Install vLLM Project and Dev Dependencies
      env:
        VLLM_BUILD_TARGET: cpu
      run: pip install -e ".[dev]"

    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --all-files --hook-stage manual